### ISSUE TITLE
What do "gi" and "bi" tags mean in a produced PAF file

### ISSUE THREAD

**Issue by shelkmike** [ekg/wflign#9]
In a PAF file which is produced by wflign, there is a string like "gi:f:0.98802 bi:f:0.897305". What do these values mean?
If "gi" is the genome identity, which of the definitions described in https://lh3.github.io/2018/11/25/on-the-definition-of-sequence-identity is used?

**Comment by AndreaGuarracino** [comment]
gi is the gap-compressed identity, while bi is the block identity. You can find their definitions here https://github.com/ekg/wflign/blob/4e2d5b607b762973f3d6efe8b547a56f041bc87a/src/wflign_wfa.cpp#L1378-L1383
bi has a similar formula to gi, but it considers the length of the indels.

**Comment by shelkmike** [comment]
Thank you
